package main

const tmpl = `// This code was autogenerated from protoc-gen-dragonboat, do not edit.
package {{ package . }}

import (
	"fmt"
	"context"

	"google.golang.org/protobuf/proto"
	sm "github.com/lni/dragonboat/v3/statemachine"
	anypb "google.golang.org/protobuf/types/known/anypb"

	"github.com/LilithGames/protoc-gen-dragonboat/runtime"
)
{{- range .Services }}
{{- $svc := .Name }}

type I{{ $svc }}DragonboatServer interface {
{{- range .Methods }}
	{{ name . }}(req *{{ name .Input }}) (*{{ name .Output }}, error)
{{- end }}
}

type I{{ $svc }}DragonboatClient interface {
{{- range .Methods }}
	{{ name . }}(ctx context.Context, req *{{ name .Input }}, opts ...runtime.DragonboatClientOption) (*{{ name .Output }}, error)
{{- end }}
}

func Dragonboat{{ $svc }}Lookup(s I{{ $svc }}DragonboatServer, query interface{}) (interface{}, error) {
	switch q := query.(type) {
{{- range .Methods }}
{{- $moptions := options . }}
{{- $mtype := default $moptions.Type "query" }}
{{- if (eq $mtype "query")}}
	case *{{ name .Input }}:
		resp, err := s.{{ name . }}(q)
		if err != nil {
			return resp, fmt.Errorf("I{{ $svc }}Server.{{ name . }}(%v) err: %w", q, err)
		}
		return resp, nil
{{- end }}
{{- end }}
	default:
		return nil, fmt.Errorf("unknown query type: %T", q)
	}
}

func Dragonboat{{ $svc }}Update(s I{{ $svc }}DragonboatServer, data []byte) (sm.Result, error) {
	req := runtime.DragonboatRequest{}
	if err := proto.Unmarshal(data, &req); err != nil {
		return runtime.MakeDragonboatResult(nil, fmt.Errorf("DragonboatRequest unmarshal err: %w", err)), nil
	}
	msg, err := anypb.UnmarshalNew(req.Data, proto.UnmarshalOptions{DiscardUnknown: true})
	if err != nil {
		return runtime.MakeDragonboatResult(nil, fmt.Errorf("DragonboatRequest.Data unmarshal err: %w", err)), nil
	}
	switch m := msg.(type) {
{{- range .Methods }}
{{- $moptions := options . }}
{{- $mtype := default $moptions.Type "query" }}
{{- if (eq $mtype "mutation")}}
	case *{{ name .Input }}:
		resp, err := s.{{ name . }}(m)
		return runtime.MakeDragonboatResult(resp, err), nil
{{- end }}
{{- end }}
	default:
		return runtime.MakeDragonboatResult(nil, fmt.Errorf("unknown mutation type: %T", m)), nil
	}
}

type {{ $svc }}DragonboatClient struct {
	client runtime.IDragonboatClient
}

func New{{ $svc }}DragonboatClient(client runtime.IDragonboatClient) I{{ $svc }}DragonboatClient {
	return &{{ $svc }}DragonboatClient{client: client}
}

{{- range .Methods }}
{{- $moptions := options . }}
{{- $mtype := default $moptions.Type "query" }}
func (it *{{ $svc }}DragonboatClient) {{ name . }}(ctx context.Context, req *{{ name .Input }}, opts ...runtime.DragonboatClientOption) (*{{ name .Output }}, error) {
{{- if (eq $mtype "query")}}
	resp, err := it.client.Query(ctx, req, opts...)
{{- else }}
	resp, err := it.client.Mutate(ctx, req, opts...)
{{- end }}
	if r, ok := resp.(*{{ name .Output }}); ok {
		return r, err
	} else if err != nil {
		return nil, err
	} else {
		return nil, fmt.Errorf("cannot parse %T response type to *{{ name .Output }}", resp)
	}
}
{{- end }}

{{- end }}
`
