package main

const tmpl = `// This code was autogenerated from protoc-gen-dragonboat, do not edit.
package {{ package . }}

import (
	// "context"
	// "fmt"

	// "github.com/golang/protobuf/proto"
)
`
