// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.20.2
// source: runtime/dragonboat.proto

package runtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DragonboatOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *DragonboatOption) Reset() {
	*x = DragonboatOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatOption) ProtoMessage() {}

func (x *DragonboatOption) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatOption.ProtoReflect.Descriptor instead.
func (*DragonboatOption) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{0}
}

func (x *DragonboatOption) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DragonboatError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DragonboatError) Reset() {
	*x = DragonboatError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatError) ProtoMessage() {}

func (x *DragonboatError) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatError.ProtoReflect.Descriptor instead.
func (*DragonboatError) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{1}
}

func (x *DragonboatError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DragonboatError) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DragonboatExample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DragonboatExample) Reset() {
	*x = DragonboatExample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatExample) ProtoMessage() {}

func (x *DragonboatExample) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatExample.ProtoReflect.Descriptor instead.
func (*DragonboatExample) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{2}
}

func (x *DragonboatExample) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DragonboatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *anypb.Any `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DragonboatRequest) Reset() {
	*x = DragonboatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatRequest) ProtoMessage() {}

func (x *DragonboatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatRequest.ProtoReflect.Descriptor instead.
func (*DragonboatRequest) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{3}
}

func (x *DragonboatRequest) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type DragonboatResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *anypb.Any       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error *DragonboatError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DragonboatResult) Reset() {
	*x = DragonboatResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatResult) ProtoMessage() {}

func (x *DragonboatResult) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatResult.ProtoReflect.Descriptor instead.
func (*DragonboatResult) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{4}
}

func (x *DragonboatResult) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DragonboatResult) GetError() *DragonboatError {
	if x != nil {
		return x.Error
	}
	return nil
}

type DragonboatVoid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DragonboatVoid) Reset() {
	*x = DragonboatVoid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatVoid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatVoid) ProtoMessage() {}

func (x *DragonboatVoid) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatVoid.ProtoReflect.Descriptor instead.
func (*DragonboatVoid) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{5}
}

var file_runtime_dragonboat_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*DragonboatOption)(nil),
		Field:         53000,
		Name:          "dragonboat.options",
		Tag:           "bytes,53000,opt,name=options",
		Filename:      "runtime/dragonboat.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional dragonboat.DragonboatOption options = 53000;
	E_Options = &file_runtime_dragonboat_proto_extTypes[0]
)

var File_runtime_dragonboat_proto protoreflect.FileDescriptor

var file_runtime_dragonboat_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e,
	0x62, 0x6f, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x72, 0x61, 0x67,
	0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x44,
	0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x27, 0x0a, 0x11, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f,
	0x61, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a,
	0x11, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6f, 0x0a, 0x10,
	0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x72, 0x61, 0x67,
	0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61,
	0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x10, 0x0a,
	0x0e, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x56, 0x6f, 0x69, 0x64, 0x3a,
	0x5b, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x9e, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e,
	0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x42, 0x36, 0x5a, 0x34,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x69, 0x6c, 0x69, 0x74,
	0x68, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2f, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runtime_dragonboat_proto_rawDescOnce sync.Once
	file_runtime_dragonboat_proto_rawDescData = file_runtime_dragonboat_proto_rawDesc
)

func file_runtime_dragonboat_proto_rawDescGZIP() []byte {
	file_runtime_dragonboat_proto_rawDescOnce.Do(func() {
		file_runtime_dragonboat_proto_rawDescData = protoimpl.X.CompressGZIP(file_runtime_dragonboat_proto_rawDescData)
	})
	return file_runtime_dragonboat_proto_rawDescData
}

var file_runtime_dragonboat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_runtime_dragonboat_proto_goTypes = []interface{}{
	(*DragonboatOption)(nil),           // 0: dragonboat.DragonboatOption
	(*DragonboatError)(nil),            // 1: dragonboat.DragonboatError
	(*DragonboatExample)(nil),          // 2: dragonboat.DragonboatExample
	(*DragonboatRequest)(nil),          // 3: dragonboat.DragonboatRequest
	(*DragonboatResult)(nil),           // 4: dragonboat.DragonboatResult
	(*DragonboatVoid)(nil),             // 5: dragonboat.DragonboatVoid
	(*anypb.Any)(nil),                  // 6: google.protobuf.Any
	(*descriptorpb.MethodOptions)(nil), // 7: google.protobuf.MethodOptions
}
var file_runtime_dragonboat_proto_depIdxs = []int32{
	6, // 0: dragonboat.DragonboatRequest.data:type_name -> google.protobuf.Any
	6, // 1: dragonboat.DragonboatResult.data:type_name -> google.protobuf.Any
	1, // 2: dragonboat.DragonboatResult.error:type_name -> dragonboat.DragonboatError
	7, // 3: dragonboat.options:extendee -> google.protobuf.MethodOptions
	0, // 4: dragonboat.options:type_name -> dragonboat.DragonboatOption
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	3, // [3:4] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_runtime_dragonboat_proto_init() }
func file_runtime_dragonboat_proto_init() {
	if File_runtime_dragonboat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runtime_dragonboat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatExample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatVoid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runtime_dragonboat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_runtime_dragonboat_proto_goTypes,
		DependencyIndexes: file_runtime_dragonboat_proto_depIdxs,
		MessageInfos:      file_runtime_dragonboat_proto_msgTypes,
		ExtensionInfos:    file_runtime_dragonboat_proto_extTypes,
	}.Build()
	File_runtime_dragonboat_proto = out.File
	file_runtime_dragonboat_proto_rawDesc = nil
	file_runtime_dragonboat_proto_goTypes = nil
	file_runtime_dragonboat_proto_depIdxs = nil
}
