// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.2
// source: runtime/dragonboat.proto

package runtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty =(prepare)> Migrating =(commit)> Upgrading =(all-upgraded)> Upgraded =(all-saved)> Empty
//
//	=(expire)> Expired   =(reset)>        Empty
//	=(reset)>  Empty
type MigrationStateType int32

const (
	MigrationStateType_Empty     MigrationStateType = 0
	MigrationStateType_Migrating MigrationStateType = 1
	MigrationStateType_Upgrading MigrationStateType = 2
	MigrationStateType_Upgraded  MigrationStateType = 3
	MigrationStateType_Expired   MigrationStateType = 4
)

// Enum value maps for MigrationStateType.
var (
	MigrationStateType_name = map[int32]string{
		0: "Empty",
		1: "Migrating",
		2: "Upgrading",
		3: "Upgraded",
		4: "Expired",
	}
	MigrationStateType_value = map[string]int32{
		"Empty":     0,
		"Migrating": 1,
		"Upgrading": 2,
		"Upgraded":  3,
		"Expired":   4,
	}
)

func (x MigrationStateType) Enum() *MigrationStateType {
	p := new(MigrationStateType)
	*p = x
	return p
}

func (x MigrationStateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationStateType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_dragonboat_proto_enumTypes[0].Descriptor()
}

func (MigrationStateType) Type() protoreflect.EnumType {
	return &file_runtime_dragonboat_proto_enumTypes[0]
}

func (x MigrationStateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationStateType.Descriptor instead.
func (MigrationStateType) EnumDescriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{0}
}

type CompressionType int32

const (
	CompressionType_None   CompressionType = 0
	CompressionType_Snappy CompressionType = 1
)

// Enum value maps for CompressionType.
var (
	CompressionType_name = map[int32]string{
		0: "None",
		1: "Snappy",
	}
	CompressionType_value = map[string]int32{
		"None":   0,
		"Snappy": 1,
	}
)

func (x CompressionType) Enum() *CompressionType {
	p := new(CompressionType)
	*p = x
	return p
}

func (x CompressionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionType) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_dragonboat_proto_enumTypes[1].Descriptor()
}

func (CompressionType) Type() protoreflect.EnumType {
	return &file_runtime_dragonboat_proto_enumTypes[1]
}

func (x CompressionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionType.Descriptor instead.
func (CompressionType) EnumDescriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{1}
}

type DragonboatOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *DragonboatOption) Reset() {
	*x = DragonboatOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatOption) ProtoMessage() {}

func (x *DragonboatOption) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatOption.ProtoReflect.Descriptor instead.
func (*DragonboatOption) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{0}
}

func (x *DragonboatOption) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DragonboatError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DragonboatError) Reset() {
	*x = DragonboatError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatError) ProtoMessage() {}

func (x *DragonboatError) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatError.ProtoReflect.Descriptor instead.
func (*DragonboatError) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{1}
}

func (x *DragonboatError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DragonboatError) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DragonboatExample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DragonboatExample) Reset() {
	*x = DragonboatExample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatExample) ProtoMessage() {}

func (x *DragonboatExample) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatExample.ProtoReflect.Descriptor instead.
func (*DragonboatExample) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{2}
}

func (x *DragonboatExample) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DragonboatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *anypb.Any `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DragonboatRequest) Reset() {
	*x = DragonboatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatRequest) ProtoMessage() {}

func (x *DragonboatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatRequest.ProtoReflect.Descriptor instead.
func (*DragonboatRequest) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{3}
}

func (x *DragonboatRequest) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type DragonboatResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *anypb.Any       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error *DragonboatError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DragonboatResult) Reset() {
	*x = DragonboatResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatResult) ProtoMessage() {}

func (x *DragonboatResult) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatResult.ProtoReflect.Descriptor instead.
func (*DragonboatResult) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{4}
}

func (x *DragonboatResult) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DragonboatResult) GetError() *DragonboatError {
	if x != nil {
		return x.Error
	}
	return nil
}

type DragonboatVoid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DragonboatVoid) Reset() {
	*x = DragonboatVoid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatVoid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatVoid) ProtoMessage() {}

func (x *DragonboatVoid) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatVoid.ProtoReflect.Descriptor instead.
func (*DragonboatVoid) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{5}
}

type MigrationNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId  uint64          `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version string          `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Nodes   map[uint64]bool `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *MigrationNode) Reset() {
	*x = MigrationNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationNode) ProtoMessage() {}

func (x *MigrationNode) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationNode.ProtoReflect.Descriptor instead.
func (*MigrationNode) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{6}
}

func (x *MigrationNode) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *MigrationNode) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MigrationNode) GetNodes() map[uint64]bool {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type MigrationNodeWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node  *MigrationNode `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Epoch uint64         `protobuf:"varint,2,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
}

func (x *MigrationNodeWrapper) Reset() {
	*x = MigrationNodeWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationNodeWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationNodeWrapper) ProtoMessage() {}

func (x *MigrationNodeWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationNodeWrapper.ProtoReflect.Descriptor instead.
func (*MigrationNodeWrapper) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{7}
}

func (x *MigrationNodeWrapper) GetNode() *MigrationNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *MigrationNodeWrapper) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type MigrationState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         MigrationStateType               `protobuf:"varint,1,opt,name=type,proto3,enum=dragonboat.MigrationStateType" json:"type,omitempty"`
	Version      string                           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Expire       uint64                           `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	Epoch        uint64                           `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	NodeUpgraded map[uint64]*MigrationNodeWrapper `protobuf:"bytes,5,rep,name=node_upgraded,json=nodeUpgraded,proto3" json:"node_upgraded,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NodeSaved    map[uint64]*MigrationNodeWrapper `protobuf:"bytes,6,rep,name=node_saved,json=nodeSaved,proto3" json:"node_saved,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StateIndex   uint64                           `protobuf:"varint,7,opt,name=state_index,json=stateIndex,proto3" json:"state_index,omitempty"`
}

func (x *MigrationState) Reset() {
	*x = MigrationState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationState) ProtoMessage() {}

func (x *MigrationState) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationState.ProtoReflect.Descriptor instead.
func (*MigrationState) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{8}
}

func (x *MigrationState) GetType() MigrationStateType {
	if x != nil {
		return x.Type
	}
	return MigrationStateType_Empty
}

func (x *MigrationState) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MigrationState) GetExpire() uint64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *MigrationState) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *MigrationState) GetNodeUpgraded() map[uint64]*MigrationNodeWrapper {
	if x != nil {
		return x.NodeUpgraded
	}
	return nil
}

func (x *MigrationState) GetNodeSaved() map[uint64]*MigrationNodeWrapper {
	if x != nil {
		return x.NodeSaved
	}
	return nil
}

func (x *MigrationState) GetStateIndex() uint64 {
	if x != nil {
		return x.StateIndex
	}
	return 0
}

type MigrationStateView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         MigrationStateType               `protobuf:"varint,1,opt,name=type,proto3,enum=dragonboat.MigrationStateType" json:"type,omitempty"`
	Version      string                           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Expire       uint64                           `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	Epoch        uint64                           `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	NodeUpgraded map[uint64]*MigrationNodeWrapper `protobuf:"bytes,5,rep,name=node_upgraded,json=nodeUpgraded,proto3" json:"node_upgraded,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NodeSaved    map[uint64]*MigrationNodeWrapper `protobuf:"bytes,6,rep,name=node_saved,json=nodeSaved,proto3" json:"node_saved,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StateIndex   uint64                           `protobuf:"varint,7,opt,name=state_index,json=stateIndex,proto3" json:"state_index,omitempty"`
}

func (x *MigrationStateView) Reset() {
	*x = MigrationStateView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationStateView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationStateView) ProtoMessage() {}

func (x *MigrationStateView) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationStateView.ProtoReflect.Descriptor instead.
func (*MigrationStateView) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{9}
}

func (x *MigrationStateView) GetType() MigrationStateType {
	if x != nil {
		return x.Type
	}
	return MigrationStateType_Empty
}

func (x *MigrationStateView) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MigrationStateView) GetExpire() uint64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *MigrationStateView) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *MigrationStateView) GetNodeUpgraded() map[uint64]*MigrationNodeWrapper {
	if x != nil {
		return x.NodeUpgraded
	}
	return nil
}

func (x *MigrationStateView) GetNodeSaved() map[uint64]*MigrationNodeWrapper {
	if x != nil {
		return x.NodeSaved
	}
	return nil
}

func (x *MigrationStateView) GetStateIndex() uint64 {
	if x != nil {
		return x.StateIndex
	}
	return 0
}

type Migration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State           []byte          `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	CompressionType CompressionType `protobuf:"varint,2,opt,name=compression_type,json=compressionType,proto3,enum=dragonboat.CompressionType" json:"compression_type,omitempty"`
}

func (x *Migration) Reset() {
	*x = Migration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Migration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Migration) ProtoMessage() {}

func (x *Migration) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Migration.ProtoReflect.Descriptor instead.
func (*Migration) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{10}
}

func (x *Migration) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Migration) GetCompressionType() CompressionType {
	if x != nil {
		return x.CompressionType
	}
	return CompressionType_None
}

type DragonboatPrepareMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompressionType CompressionType `protobuf:"varint,1,opt,name=compression_type,json=compressionType,proto3,enum=dragonboat.CompressionType" json:"compression_type,omitempty"`
	Expire          uint64          `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
}

func (x *DragonboatPrepareMigrationRequest) Reset() {
	*x = DragonboatPrepareMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatPrepareMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatPrepareMigrationRequest) ProtoMessage() {}

func (x *DragonboatPrepareMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatPrepareMigrationRequest.ProtoReflect.Descriptor instead.
func (*DragonboatPrepareMigrationRequest) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{11}
}

func (x *DragonboatPrepareMigrationRequest) GetCompressionType() CompressionType {
	if x != nil {
		return x.CompressionType
	}
	return CompressionType_None
}

func (x *DragonboatPrepareMigrationRequest) GetExpire() uint64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type DragonboatPrepareMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Migration *Migration `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
}

func (x *DragonboatPrepareMigrationResponse) Reset() {
	*x = DragonboatPrepareMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatPrepareMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatPrepareMigrationResponse) ProtoMessage() {}

func (x *DragonboatPrepareMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatPrepareMigrationResponse.ProtoReflect.Descriptor instead.
func (*DragonboatPrepareMigrationResponse) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{12}
}

func (x *DragonboatPrepareMigrationResponse) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

type DragonboatCommitMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Migration *Migration `protobuf:"bytes,1,opt,name=migration,proto3" json:"migration,omitempty"`
}

func (x *DragonboatCommitMigrationRequest) Reset() {
	*x = DragonboatCommitMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatCommitMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatCommitMigrationRequest) ProtoMessage() {}

func (x *DragonboatCommitMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatCommitMigrationRequest.ProtoReflect.Descriptor instead.
func (*DragonboatCommitMigrationRequest) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{13}
}

func (x *DragonboatCommitMigrationRequest) GetMigration() *Migration {
	if x != nil {
		return x.Migration
	}
	return nil
}

type DragonboatCommitMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MigrationStateType `protobuf:"varint,1,opt,name=type,proto3,enum=dragonboat.MigrationStateType" json:"type,omitempty"`
}

func (x *DragonboatCommitMigrationResponse) Reset() {
	*x = DragonboatCommitMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatCommitMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatCommitMigrationResponse) ProtoMessage() {}

func (x *DragonboatCommitMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatCommitMigrationResponse.ProtoReflect.Descriptor instead.
func (*DragonboatCommitMigrationResponse) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{14}
}

func (x *DragonboatCommitMigrationResponse) GetType() MigrationStateType {
	if x != nil {
		return x.Type
	}
	return MigrationStateType_Empty
}

type DragonboatUpdateMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *MigrationNode `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *DragonboatUpdateMigrationRequest) Reset() {
	*x = DragonboatUpdateMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatUpdateMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatUpdateMigrationRequest) ProtoMessage() {}

func (x *DragonboatUpdateMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatUpdateMigrationRequest.ProtoReflect.Descriptor instead.
func (*DragonboatUpdateMigrationRequest) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{15}
}

func (x *DragonboatUpdateMigrationRequest) GetNode() *MigrationNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type DragonboatUpdateMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated uint64 `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *DragonboatUpdateMigrationResponse) Reset() {
	*x = DragonboatUpdateMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatUpdateMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatUpdateMigrationResponse) ProtoMessage() {}

func (x *DragonboatUpdateMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatUpdateMigrationResponse.ProtoReflect.Descriptor instead.
func (*DragonboatUpdateMigrationResponse) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{16}
}

func (x *DragonboatUpdateMigrationResponse) GetUpdated() uint64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type DragonboatCompleteMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *MigrationNode `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *DragonboatCompleteMigrationRequest) Reset() {
	*x = DragonboatCompleteMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatCompleteMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatCompleteMigrationRequest) ProtoMessage() {}

func (x *DragonboatCompleteMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatCompleteMigrationRequest.ProtoReflect.Descriptor instead.
func (*DragonboatCompleteMigrationRequest) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{17}
}

func (x *DragonboatCompleteMigrationRequest) GetNode() *MigrationNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type DragonboatCompleteMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated uint64 `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *DragonboatCompleteMigrationResponse) Reset() {
	*x = DragonboatCompleteMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatCompleteMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatCompleteMigrationResponse) ProtoMessage() {}

func (x *DragonboatCompleteMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatCompleteMigrationResponse.ProtoReflect.Descriptor instead.
func (*DragonboatCompleteMigrationResponse) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{18}
}

func (x *DragonboatCompleteMigrationResponse) GetUpdated() uint64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type DragonboatResetMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DragonboatResetMigrationRequest) Reset() {
	*x = DragonboatResetMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatResetMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatResetMigrationRequest) ProtoMessage() {}

func (x *DragonboatResetMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatResetMigrationRequest.ProtoReflect.Descriptor instead.
func (*DragonboatResetMigrationRequest) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{19}
}

type DragonboatResetMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DragonboatResetMigrationResponse) Reset() {
	*x = DragonboatResetMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatResetMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatResetMigrationResponse) ProtoMessage() {}

func (x *DragonboatResetMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatResetMigrationResponse.ProtoReflect.Descriptor instead.
func (*DragonboatResetMigrationResponse) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{20}
}

type DragonboatQueryMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DragonboatQueryMigrationRequest) Reset() {
	*x = DragonboatQueryMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatQueryMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatQueryMigrationRequest) ProtoMessage() {}

func (x *DragonboatQueryMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatQueryMigrationRequest.ProtoReflect.Descriptor instead.
func (*DragonboatQueryMigrationRequest) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{21}
}

type DragonboatQueryMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View *MigrationStateView `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
}

func (x *DragonboatQueryMigrationResponse) Reset() {
	*x = DragonboatQueryMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatQueryMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatQueryMigrationResponse) ProtoMessage() {}

func (x *DragonboatQueryMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatQueryMigrationResponse.ProtoReflect.Descriptor instead.
func (*DragonboatQueryMigrationResponse) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{22}
}

func (x *DragonboatQueryMigrationResponse) GetView() *MigrationStateView {
	if x != nil {
		return x.View
	}
	return nil
}

type DragonboatQueryIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DragonboatQueryIndexRequest) Reset() {
	*x = DragonboatQueryIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatQueryIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatQueryIndexRequest) ProtoMessage() {}

func (x *DragonboatQueryIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatQueryIndexRequest.ProtoReflect.Descriptor instead.
func (*DragonboatQueryIndexRequest) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{23}
}

type DragonboatQueryIndexResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateIndex uint64 `protobuf:"varint,1,opt,name=state_index,json=stateIndex,proto3" json:"state_index,omitempty"`
}

func (x *DragonboatQueryIndexResponse) Reset() {
	*x = DragonboatQueryIndexResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatQueryIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatQueryIndexResponse) ProtoMessage() {}

func (x *DragonboatQueryIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatQueryIndexResponse.ProtoReflect.Descriptor instead.
func (*DragonboatQueryIndexResponse) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{24}
}

func (x *DragonboatQueryIndexResponse) GetStateIndex() uint64 {
	if x != nil {
		return x.StateIndex
	}
	return 0
}

type DragonboatRepairMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Confirm        string `protobuf:"bytes,1,opt,name=confirm,proto3" json:"confirm,omitempty"`
	CurrentVersion string `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
}

func (x *DragonboatRepairMigrationRequest) Reset() {
	*x = DragonboatRepairMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatRepairMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatRepairMigrationRequest) ProtoMessage() {}

func (x *DragonboatRepairMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatRepairMigrationRequest.ProtoReflect.Descriptor instead.
func (*DragonboatRepairMigrationRequest) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{25}
}

func (x *DragonboatRepairMigrationRequest) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

func (x *DragonboatRepairMigrationRequest) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

type DragonboatRepairMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DragonboatRepairMigrationResponse) Reset() {
	*x = DragonboatRepairMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_dragonboat_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DragonboatRepairMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DragonboatRepairMigrationResponse) ProtoMessage() {}

func (x *DragonboatRepairMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_dragonboat_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DragonboatRepairMigrationResponse.ProtoReflect.Descriptor instead.
func (*DragonboatRepairMigrationResponse) Descriptor() ([]byte, []int) {
	return file_runtime_dragonboat_proto_rawDescGZIP(), []int{26}
}

var file_runtime_dragonboat_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*DragonboatOption)(nil),
		Field:         53000,
		Name:          "dragonboat.options",
		Tag:           "bytes,53000,opt,name=options",
		Filename:      "runtime/dragonboat.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional dragonboat.DragonboatOption options = 53000;
	E_Options = &file_runtime_dragonboat_proto_extTypes[0]
)

var File_runtime_dragonboat_proto protoreflect.FileDescriptor

var file_runtime_dragonboat_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e,
	0x62, 0x6f, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x72, 0x61, 0x67,
	0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x44,
	0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x27, 0x0a, 0x11, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f,
	0x61, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a,
	0x11, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6f, 0x0a, 0x10,
	0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x72, 0x61, 0x67,
	0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61,
	0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x10, 0x0a,
	0x0e, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x56, 0x6f, 0x69, 0x64, 0x22,
	0xb8, 0x01, 0x0a, 0x0d, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74,
	0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x1a, 0x38, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5b, 0x0a, 0x14, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x57, 0x72, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x12, 0x2d, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x22, 0x8d, 0x04, 0x0a, 0x0e, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f,
	0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x51, 0x0a, 0x0d, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x75,
	0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x70,
	0x67, 0x72, 0x61, 0x64, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x6e, 0x6f, 0x64,
	0x65, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x64, 0x12, 0x48, 0x0a, 0x0a, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x73, 0x61, 0x76, 0x65, 0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x61,
	0x76, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x61,
	0x76, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x1a, 0x61, 0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x70, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x72, 0x61,
	0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x5e, 0x0a, 0x0e, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x61, 0x76, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x72, 0x61,
	0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x99, 0x04, 0x0a, 0x12, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x56, 0x69, 0x65, 0x77, 0x12, 0x32,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x64,
	0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x55, 0x0a, 0x0d, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x30, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x56, 0x69, 0x65,
	0x77, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x64, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65,
	0x64, 0x12, 0x4c, 0x0a, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x61, 0x76, 0x65, 0x64, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f,
	0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x61, 0x76, 0x65, 0x64, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x53, 0x61, 0x76, 0x65, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x1a, 0x61, 0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x64,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62,
	0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64,
	0x65, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x5e, 0x0a, 0x0e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x61, 0x76, 0x65, 0x64,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62,
	0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64,
	0x65, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x69, 0x0a, 0x09, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1b, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x63,
	0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x83,
	0x01, 0x0a, 0x21, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x46, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b,
	0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x63, 0x6f, 0x6d,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x22, 0x59, 0x0a, 0x22, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f,
	0x61, 0x74, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x6d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x57, 0x0a, 0x20, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x09, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62,
	0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x57, 0x0a, 0x21, 0x44, 0x72, 0x61, 0x67,
	0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x64, 0x72,
	0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x51, 0x0a, 0x20, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74,
	0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x22, 0x3d, 0x0a, 0x21, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f,
	0x61, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x22, 0x53, 0x0a, 0x22, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61,
	0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e,
	0x62, 0x6f, 0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x3f, 0x0a, 0x23, 0x44, 0x72, 0x61, 0x67,
	0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x21, 0x0a, 0x1f, 0x44, 0x72, 0x61,
	0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x22, 0x0a, 0x20,
	0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x4d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x21, 0x0a, 0x1f, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x20, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61,
	0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f,
	0x61, 0x74, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x56, 0x69, 0x65, 0x77, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x22, 0x1d, 0x0a, 0x1b, 0x44,
	0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x1c, 0x44, 0x72,
	0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x65, 0x0a, 0x20, 0x44,
	0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x70, 0x61, 0x69, 0x72, 0x4d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x21, 0x44, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74,
	0x52, 0x65, 0x70, 0x61, 0x69, 0x72, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x58, 0x0a, 0x12, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x70, 0x67, 0x72, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x64, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x10,
	0x04, 0x2a, 0x27, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x6e, 0x61, 0x70, 0x70, 0x79, 0x10, 0x01, 0x3a, 0x5b, 0x0a, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x9e, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x64, 0x72, 0x61, 0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2e, 0x44, 0x72, 0x61, 0x67, 0x6f,
	0x6e, 0x62, 0x6f, 0x61, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x69, 0x6c, 0x69, 0x74, 0x68, 0x47, 0x61, 0x6d, 0x65,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x64, 0x72, 0x61,
	0x67, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x74, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runtime_dragonboat_proto_rawDescOnce sync.Once
	file_runtime_dragonboat_proto_rawDescData = file_runtime_dragonboat_proto_rawDesc
)

func file_runtime_dragonboat_proto_rawDescGZIP() []byte {
	file_runtime_dragonboat_proto_rawDescOnce.Do(func() {
		file_runtime_dragonboat_proto_rawDescData = protoimpl.X.CompressGZIP(file_runtime_dragonboat_proto_rawDescData)
	})
	return file_runtime_dragonboat_proto_rawDescData
}

var file_runtime_dragonboat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runtime_dragonboat_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_runtime_dragonboat_proto_goTypes = []interface{}{
	(MigrationStateType)(0),                     // 0: dragonboat.MigrationStateType
	(CompressionType)(0),                        // 1: dragonboat.CompressionType
	(*DragonboatOption)(nil),                    // 2: dragonboat.DragonboatOption
	(*DragonboatError)(nil),                     // 3: dragonboat.DragonboatError
	(*DragonboatExample)(nil),                   // 4: dragonboat.DragonboatExample
	(*DragonboatRequest)(nil),                   // 5: dragonboat.DragonboatRequest
	(*DragonboatResult)(nil),                    // 6: dragonboat.DragonboatResult
	(*DragonboatVoid)(nil),                      // 7: dragonboat.DragonboatVoid
	(*MigrationNode)(nil),                       // 8: dragonboat.MigrationNode
	(*MigrationNodeWrapper)(nil),                // 9: dragonboat.MigrationNodeWrapper
	(*MigrationState)(nil),                      // 10: dragonboat.MigrationState
	(*MigrationStateView)(nil),                  // 11: dragonboat.MigrationStateView
	(*Migration)(nil),                           // 12: dragonboat.Migration
	(*DragonboatPrepareMigrationRequest)(nil),   // 13: dragonboat.DragonboatPrepareMigrationRequest
	(*DragonboatPrepareMigrationResponse)(nil),  // 14: dragonboat.DragonboatPrepareMigrationResponse
	(*DragonboatCommitMigrationRequest)(nil),    // 15: dragonboat.DragonboatCommitMigrationRequest
	(*DragonboatCommitMigrationResponse)(nil),   // 16: dragonboat.DragonboatCommitMigrationResponse
	(*DragonboatUpdateMigrationRequest)(nil),    // 17: dragonboat.DragonboatUpdateMigrationRequest
	(*DragonboatUpdateMigrationResponse)(nil),   // 18: dragonboat.DragonboatUpdateMigrationResponse
	(*DragonboatCompleteMigrationRequest)(nil),  // 19: dragonboat.DragonboatCompleteMigrationRequest
	(*DragonboatCompleteMigrationResponse)(nil), // 20: dragonboat.DragonboatCompleteMigrationResponse
	(*DragonboatResetMigrationRequest)(nil),     // 21: dragonboat.DragonboatResetMigrationRequest
	(*DragonboatResetMigrationResponse)(nil),    // 22: dragonboat.DragonboatResetMigrationResponse
	(*DragonboatQueryMigrationRequest)(nil),     // 23: dragonboat.DragonboatQueryMigrationRequest
	(*DragonboatQueryMigrationResponse)(nil),    // 24: dragonboat.DragonboatQueryMigrationResponse
	(*DragonboatQueryIndexRequest)(nil),         // 25: dragonboat.DragonboatQueryIndexRequest
	(*DragonboatQueryIndexResponse)(nil),        // 26: dragonboat.DragonboatQueryIndexResponse
	(*DragonboatRepairMigrationRequest)(nil),    // 27: dragonboat.DragonboatRepairMigrationRequest
	(*DragonboatRepairMigrationResponse)(nil),   // 28: dragonboat.DragonboatRepairMigrationResponse
	nil,                                // 29: dragonboat.MigrationNode.NodesEntry
	nil,                                // 30: dragonboat.MigrationState.NodeUpgradedEntry
	nil,                                // 31: dragonboat.MigrationState.NodeSavedEntry
	nil,                                // 32: dragonboat.MigrationStateView.NodeUpgradedEntry
	nil,                                // 33: dragonboat.MigrationStateView.NodeSavedEntry
	(*anypb.Any)(nil),                  // 34: google.protobuf.Any
	(*descriptorpb.MethodOptions)(nil), // 35: google.protobuf.MethodOptions
}
var file_runtime_dragonboat_proto_depIdxs = []int32{
	34, // 0: dragonboat.DragonboatRequest.data:type_name -> google.protobuf.Any
	34, // 1: dragonboat.DragonboatResult.data:type_name -> google.protobuf.Any
	3,  // 2: dragonboat.DragonboatResult.error:type_name -> dragonboat.DragonboatError
	29, // 3: dragonboat.MigrationNode.nodes:type_name -> dragonboat.MigrationNode.NodesEntry
	8,  // 4: dragonboat.MigrationNodeWrapper.node:type_name -> dragonboat.MigrationNode
	0,  // 5: dragonboat.MigrationState.type:type_name -> dragonboat.MigrationStateType
	30, // 6: dragonboat.MigrationState.node_upgraded:type_name -> dragonboat.MigrationState.NodeUpgradedEntry
	31, // 7: dragonboat.MigrationState.node_saved:type_name -> dragonboat.MigrationState.NodeSavedEntry
	0,  // 8: dragonboat.MigrationStateView.type:type_name -> dragonboat.MigrationStateType
	32, // 9: dragonboat.MigrationStateView.node_upgraded:type_name -> dragonboat.MigrationStateView.NodeUpgradedEntry
	33, // 10: dragonboat.MigrationStateView.node_saved:type_name -> dragonboat.MigrationStateView.NodeSavedEntry
	1,  // 11: dragonboat.Migration.compression_type:type_name -> dragonboat.CompressionType
	1,  // 12: dragonboat.DragonboatPrepareMigrationRequest.compression_type:type_name -> dragonboat.CompressionType
	12, // 13: dragonboat.DragonboatPrepareMigrationResponse.migration:type_name -> dragonboat.Migration
	12, // 14: dragonboat.DragonboatCommitMigrationRequest.migration:type_name -> dragonboat.Migration
	0,  // 15: dragonboat.DragonboatCommitMigrationResponse.type:type_name -> dragonboat.MigrationStateType
	8,  // 16: dragonboat.DragonboatUpdateMigrationRequest.node:type_name -> dragonboat.MigrationNode
	8,  // 17: dragonboat.DragonboatCompleteMigrationRequest.node:type_name -> dragonboat.MigrationNode
	11, // 18: dragonboat.DragonboatQueryMigrationResponse.view:type_name -> dragonboat.MigrationStateView
	9,  // 19: dragonboat.MigrationState.NodeUpgradedEntry.value:type_name -> dragonboat.MigrationNodeWrapper
	9,  // 20: dragonboat.MigrationState.NodeSavedEntry.value:type_name -> dragonboat.MigrationNodeWrapper
	9,  // 21: dragonboat.MigrationStateView.NodeUpgradedEntry.value:type_name -> dragonboat.MigrationNodeWrapper
	9,  // 22: dragonboat.MigrationStateView.NodeSavedEntry.value:type_name -> dragonboat.MigrationNodeWrapper
	35, // 23: dragonboat.options:extendee -> google.protobuf.MethodOptions
	2,  // 24: dragonboat.options:type_name -> dragonboat.DragonboatOption
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	24, // [24:25] is the sub-list for extension type_name
	23, // [23:24] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_runtime_dragonboat_proto_init() }
func file_runtime_dragonboat_proto_init() {
	if File_runtime_dragonboat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runtime_dragonboat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatExample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatVoid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationNodeWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationStateView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Migration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatPrepareMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatPrepareMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatCommitMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatCommitMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatUpdateMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatUpdateMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatCompleteMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatCompleteMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatResetMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatResetMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatQueryMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatQueryMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatQueryIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatQueryIndexResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatRepairMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_dragonboat_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DragonboatRepairMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runtime_dragonboat_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_runtime_dragonboat_proto_goTypes,
		DependencyIndexes: file_runtime_dragonboat_proto_depIdxs,
		EnumInfos:         file_runtime_dragonboat_proto_enumTypes,
		MessageInfos:      file_runtime_dragonboat_proto_msgTypes,
		ExtensionInfos:    file_runtime_dragonboat_proto_extTypes,
	}.Build()
	File_runtime_dragonboat_proto = out.File
	file_runtime_dragonboat_proto_rawDesc = nil
	file_runtime_dragonboat_proto_goTypes = nil
	file_runtime_dragonboat_proto_depIdxs = nil
}
