// This code was autogenerated from protoc-gen-dragonboat, do not edit.
package testdata

import (
	"fmt"
	// "context"

	sm "github.com/lni/dragonboat/v3/statemachine"
	"google.golang.org/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"

	"github.com/LilithGames/protoc-gen-dragonboat/runtime"
)

type ITestServer interface {
	QueryAddressBook(req *QueryAddressBookRequest) (*QueryAddressBookResponse, error)
	MutateAddressBook(req *MutateAddressBookRequest) (*MutateAddressBookResponse, error)
}

func DragonboatTestLookup(s ITestServer, query interface{}) (interface{}, error) {
	switch q := query.(type) {
	case *QueryAddressBookRequest:
		resp, err := s.QueryAddressBook(q)
		if err != nil {
			return resp, fmt.Errorf("ITestServer.QueryAddressBook(%v) err: %w", q, err)
		}
		return resp, nil
	default:
		return nil, fmt.Errorf("unknown query type: %T", q)
	}
}

func DragonboatTestUpdate(s ITestServer, data []byte) (sm.Result, error) {
	req := runtime.DragonboatRequest{}
	if err := proto.Unmarshal(data, &req); err != nil {
		return runtime.MakeDragonboatResult(nil, fmt.Errorf("DragonboatRequest unmarshal err: %w", err)), nil
	}
	msg, err := anypb.UnmarshalNew(req.Data, proto.UnmarshalOptions{DiscardUnknown: true})
	if err != nil {
		return runtime.MakeDragonboatResult(nil, fmt.Errorf("DragonboatRequest.Data unmarshal err: %w", err)), nil
	}
	switch m := msg.(type) {
	case *MutateAddressBookRequest:
		resp, err := s.MutateAddressBook(m)
		return runtime.MakeDragonboatResult(resp, err), nil
	default:
		return runtime.MakeDragonboatResult(nil, fmt.Errorf("unknown mutation type: %T", m)), nil
	}
}
